=== IsmaelCussac/xml_master/SiteMaster/master-dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Entités -->
<!ENTITY % id "id ID #IMPLIED">
<!ENTITY % ref "ref IDREF #IMPLIED">
<!ENTITY  %  site
             "site (Luminy|Saint-Jérome|Luminy_Saint-Jérome) #IMPLIED">
<!ENTITY dom.amu "univ-amu.fr">
<!ENTITY url.lif "http://pageperso.lif.univ-mrs.fr/~">
<!ENTITY  %  unite
             "unite (Obligatoire|Option|Bonus) #IMPLIED">            
<!ENTITY  %  final
             "final (Recherche|Professionnelle) #IMPLIED">


<!-- Racine -->
<!ELEMENT master_info (intervenants, master, unites)>

<!-- Liste d'intervenants -->
<!ELEMENT intervenants (intervenant+)>
<!ELEMENT intervenant (idext, nom_inter, prenom_inter, mail?, site?)>
<!ATTLIST intervenant %id;>

<!-- Spécialité -->
<!ELEMENT master (specialite+, parcours+)>
<!ELEMENT specialite (nom_spe, responsable+, ref_parcours+, description, debouche, finalite)>
<!ATTLIST specialite %id;>

<!-- Parcours -->
<!ELEMENT parcours (nom_parc, semestre+, responsable*, description, ref_intervenant*, lieu_parc)>
<!ATTLIST parcours %id;>

<!-- Semestre -->
<!ELEMENT semestre (nom_sem, bloc_ue+)>
<!ELEMENT bloc_ue (nom_bloc_ue, ref_ue+)>


<!-- UE -->
<!ELEMENT unites (ue+)>
<!ELEMENT ue (nom_ue, nom_identificateur, nb_credits, ref_intervenant*, resume, plan?, lieu_ue?)>
<!ATTLIST ue %id;>


<!-- Feuilles -->

<!ELEMENT ref_parcours     (#PCDATA)> 
<!ELEMENT idext     (#PCDATA)>  
<!ELEMENT nom_inter     (#PCDATA)>  
<!ELEMENT prenom_inter     (#PCDATA)> 
<!ELEMENT mail     (#PCDATA)>   
<!ELEMENT site     (#PCDATA)>   
<!ELEMENT nom_ue     (#PCDATA)> 
<!ELEMENT nom_identificateur     (#PCDATA)>
<!ELEMENT ref_ue     (#PCDATA)> 
<!ELEMENT nb_credits     (#PCDATA)>
<!ELEMENT resume     ANY>
<!ELEMENT plan     (#PCDATA)>
<!ELEMENT lieu_ue    (#PCDATA) >
<!ATTLIST lieu_ue
    %site;
    >
<!ELEMENT nom_sem     (#PCDATA)>
<!ELEMENT ref_intervenant     (#PCDATA)>
<!ELEMENT nom_spe     (#PCDATA)> 
<!ELEMENT nom_parc     (#PCDATA)>
<!ELEMENT description     ANY>
<!ELEMENT debouche     ANY>
<!ELEMENT responsable     (#PCDATA)>
<!ATTLIST  responsable  
	%ref;
	>
<!ELEMENT finalite     (#PCDATA)>            
<!ATTLIST finalite
    %final;
    >
<!ELEMENT lieu_parc    (#PCDATA) >                
<!ATTLIST lieu_parc
    %site;
    >
<!ELEMENT nom_bloc_ue     (#PCDATA)>
<!ATTLIST nom_bloc_ue
    %unite;
    >

<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT li	(#PCDATA|b|i|u|br|ol|ul)* >
<!ELEMENT p		(#PCDATA|b|i|u|br|ol|ul)* >
<!ELEMENT b		(#PCDATA) >
<!ELEMENT i		(#PCDATA) >
<!ELEMENT u		(#PCDATA) >
<!ELEMENT br		EMPTY >

=== IsmaelCussac/xml_master/SiteMaster/master-gen.xml
<?xml version="1.0"?>
<!DOCTYPE master_info SYSTEM "master-dtd.dtd">
<master_info>
  <intervenants>
    <intervenant id="IN10388">
      <idext>favre.b</idext>
      <nom_inter>FAVRE</nom_inter>
      <prenom_inter>Benoit</prenom_inter>
      <mail>benoit.favre@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN12068">
      <idext>aucheupl</idext>
      <nom_inter>HABET</nom_inter>
      <prenom_inter>Djamal</prenom_inter>
      <mail>djamal.habet@univ-amu.fr</mail>
      <site>http://pageperso.lif.univ-mrs.fr/~djamal.habet/</site>
    </intervenant>
    <intervenant id="IN12316">
      <idext>demongodini</idext>
      <nom_inter>DEMONGODIN</nom_inter>
      <prenom_inter>Isabelle</prenom_inter>
      <mail>isabel.demongodin@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN12544">
      <idext>omar.boucelma</idext>
      <nom_inter>BOUCELMA</nom_inter>
      <prenom_inter>Omar</prenom_inter>
      <mail>omar.boucelma@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN12632">
      <idext>tauclui3</idext>
      <nom_inter>OLIVETTI</nom_inter>
      <prenom_inter>Nicola</prenom_inter>
      <mail>nicola.olivetti@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN12834">
      <idext>rachid.outbib</idext>
      <nom_inter>OUTBIB</nom_inter>
      <prenom_inter>Rachid</prenom_inter>
      <mail>rachid.outbib@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN12969">
      <idext>lydie.rene</idext>
      <nom_inter>RENE CHABAROT</nom_inter>
      <prenom_inter>Lydie</prenom_inter>
      <mail>lydie.rene@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN13794">
      <idext>folive</idext>
      <nom_inter>OLIVE</nom_inter>
      <prenom_inter>Frederic</prenom_inter>
      <mail>frederic.olive@univ-amu.fr</mail>
      <site>http://pageperso.lif.univ-mrs.fr/~frederic.olive/</site>
    </intervenant>
    <intervenant id="IN14758">
      <idext>broche.m</idext>
      <nom_inter>BROCHE</nom_inter>
      <prenom_inter>Martine</prenom_inter>
      <mail>martine.broche@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN16209">
      <idext>ralaivola.h</idext>
      <nom_inter>RALAIVOLA</nom_inter>
      <prenom_inter>Hery Liva</prenom_inter>
      <mail>hery-liva.ralaivola@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN16625">
      <idext>ssellami</idext>
      <nom_inter>SELLAMI</nom_inter>
      <prenom_inter>Sana</prenom_inter>
      <mail>sana.sellami@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN17708">
      <idext>smiche01</idext>
      <nom_inter>MICHEL</nom_inter>
      <prenom_inter>Stephane</prenom_inter>
      <mail/>
    </intervenant>
    <intervenant id="IN18">
      <idext>massat</idext>
      <nom_inter>MASSAT</nom_inter>
      <prenom_inter>Jean Luc</prenom_inter>
      <mail>jean-luc.massat@univ-amu.fr</mail>
      <site>http://www.dil.univ-mrs.fr/~massat/copie/index.html</site>
    </intervenant>
    <intervenant id="IN2563">
      <idext>godard</idext>
      <nom_inter>GODARD</nom_inter>
      <prenom_inter>Emmanuel</prenom_inter>
      <mail>emmanuel.godard@univ-amu.fr</mail>
      <site>http://pageperso.lif.univ-mrs.fr/~emmanuel.godard/</site>
    </intervenant>
    <intervenant id="IN3524">
      <idext>lugiez</idext>
      <nom_inter>LUGIEZ</nom_inter>
      <prenom_inter>Denis</prenom_inter>
      <mail>denis.lugiez@univ-amu.fr</mail>
      <site>http://pageperso.lif.univ-mrs.fr/~denis.lugiez/</site>
    </intervenant>
    <intervenant id="IN616">
      <idext>agopian</idext>
      <nom_inter>AGOPIAN</nom_inter>
      <prenom_inter>Roland</prenom_inter>
      <mail>roland.agopian@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN6213">
      <idext>alaboure</idext>
      <nom_inter>LABOUREL</nom_inter>
      <prenom_inter>Arnaud</prenom_inter>
      <mail>arnaud.labourel@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN7001">
      <idext>creignou</idext>
      <nom_inter>CREIGNOU</nom_inter>
      <prenom_inter>Nadia</prenom_inter>
      <mail>nadia.creignou@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN7680">
      <idext>lai</idext>
      <nom_inter>LAI</nom_inter>
      <prenom_inter>Claude</prenom_inter>
      <mail>claude.lai@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN7722">
      <idext>novelli</idext>
      <nom_inter>NOVELLI</nom_inter>
      <prenom_inter>Noel</prenom_inter>
      <mail>noel.novelli@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN7931">
      <idext>calabrese</idext>
      <nom_inter>RISCH</nom_inter>
      <prenom_inter>Sylvie</prenom_inter>
      <mail>sylvie.risch@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN8006">
      <idext>boi</idext>
      <nom_inter>BOI</nom_inter>
      <prenom_inter>Jean Marc</prenom_inter>
      <mail>jean-marc.boi@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN8086">
      <idext>vaxes</idext>
      <nom_inter>VAXES</nom_inter>
      <prenom_inter>Yann</prenom_inter>
      <mail>yann.vaxes@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="IN9224">
      <idext>morin.r</idext>
      <nom_inter>MORIN</nom_inter>
      <prenom_inter>Remi</prenom_inter>
      <mail>remi.morin@univ-amu.fr</mail>
      <site>http://pageperso.lif.univ-mrs.fr/~remi.morin/</site>
    </intervenant>
    <intervenant id="IN9941">
      <idext>bechet.f</idext>
      <nom_inter>BECHET</nom_inter>
      <prenom_inter>Frederic</prenom_inter>
      <mail>frederic.bechet@univ-amu.fr</mail>
    </intervenant>
  </intervenants>
  <master>
    <specialite id="SPSIN5A">
      <nom_spe>Informatique fondamentale (IF)</nom_spe>
      <responsable ref="IN16209">RALAIVOLA</responsable>
      <ref_parcours>PRSIN4T0</ref_parcours>
      <ref_parcours>PRSIN5A0</ref_parcours>
      <description>
      
          L'objectif de la spécialité Informatique Fondamentale est de donner des connaissances solides dans le domaine des fondements de l'informatique.
          
          Il s'agit d'acquérir des connaissances sur les concepts et les méthodes dans les thèmes couverts par le laboratoire d'informatique fondamentale.
        
    </description>
      <debouche>
      
          Emplois recherche et développement dans des entreprises privées ou des établissements publics, ou emploi d'enseignant-chercheur pour les étudiants qui poursuivent en thèse.
        
    </debouche>
      <finalite>R</finalite>
    </specialite>
    <specialite id="SPSIN5B">
      <nom_spe>Sciences de l'information et des systèmes</nom_spe>
      <responsable ref="IN12316">DEMONGODIN</responsable>
      <ref_parcours>PRSIN4T0</ref_parcours>
      <ref_parcours>PRSIN5B1</ref_parcours>
      <ref_parcours>PRSIN5B2</ref_parcours>
      <ref_parcours>PRSIN5B3</ref_parcours>
      <description>
      
          
            Compétences scientifiques, techniques et technologique relevant du domaine l'Informatique, de l'Imagerie Numérique, de l'Automatique et d'une façon générale des sciences de l'information et des systèmes.
          
          
            Aptitude à la recherche et à la veille technologique
          
        
    </description>
      <debouche>
      
          Enseignants, Chercheurs et ingéniers de recherche, experts, chef de projets R&amp;D, Informaticiens et Automaticien spécialistes :
        
      
          
            en systèmes d'information,
          
          
            intelligence artificielle,
          
          
            génie logicielle,
          
          
            en Imagerie numérique,
          
          
            en systèmes dynamiques complexes.
          
        
    </debouche>
      <finalite>R</finalite>
    </specialite>
    <specialite id="SPSIN5C">
      <nom_spe>Fiabilité, sécurité et intégration logicielle (FSIL)</nom_spe>
      <responsable ref="IN3524">LUGIEZ</responsable>
      <responsable ref="IN18">MASSAT</responsable>
      <ref_parcours>PRSIN4T0</ref_parcours>
      <ref_parcours>PRSIN5C1</ref_parcours>
      <ref_parcours>PRSIN5C2</ref_parcours>
      <description>
      
          L'objectif de la spécialité FSIL est de former des étudiants afin qu'ils puissent concevoir, réaliser, valider et mettre en exploitation des logiciels. Pour ce faire, ils devront connaître les concepts, les outils et les méthodes liés au développement de logiciels. Les aspects de qualité, de sécurité et de bonne intégration dans des environnements informatiques complexes seront les points forts de la formation.
        
    </description>
      <debouche>
      
          Les secteurs d'activités concernés sont tous ceux qui utilisent et développent des applications informatiques, avec des pré-requis forts de fiabilité (qualité logicielle) et sécurité (protection contre les actions malveillantes). Les SSII forment une part importante des débouchés mais de grands groupes de l'industrie (transports, électronique, défense,...) ou des services (banques, assurance,..) sont également des employeurs. Les PME innovantes en informatique (éditeurs, prestataires de services, ...) et les collectivités territoriales et établissements publics complètent le secteur d'activité.
        
      
          Métiers visés pour le parcours FSI :
        
      
          
            Ingénieur études et développement,
          
          
            Responsable réseaux,
          
          
            Responsable systèmes et sécurité,
          
          
            Ingénieur qualité.
          
        
      
          Métiers visés par le parcours ISL :
        
      
          
            Ingénieur études et développement,
          
          
            Architecte logiciel,
          
          
            Ingénieur en système d'information,
          
          
            Expert technique ou fonctionnel.
          
        
    </debouche>
      <finalite>P</finalite>
    </specialite>
    <specialite id="SPSIN5D">
