=== IsmaelCussac/xml_master/SiteMaster/Site.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Entités -->
<!ENTITY % id "id ID #IMPLIED">
<!ENTITY  %  site
             "site (Luminy|Saint-Jérome|Luminy_Saint-Jérome) #IMPLIED">
<!ENTITY dom.amu "@univ-amu.fr">
<!ENTITY url.lif "http://pageperso.lif.univ-mrs.fr/~">
<!ENTITY  %  unite
             "unite (Obligatoire|Option|Bonus) #IMPLIED">            
<!ENTITY  %  final
             "final (Recherche|Professionnelle) #IMPLIED">


<!-- Racine -->
<!ELEMENT master_info (intervenants, master+, unites)>

<!-- Liste d'intervenants -->
<!ELEMENT intervenants (intervenant+)>
<!ELEMENT intervenant (nom_inter, mail, site)>
<!ATTLIST intervenant %id;>
    
<!-- Master -->
<!ELEMENT master (nom_master, specialite+)>
<!ATTLIST master %id;>

<!-- Spécialité -->
<!ELEMENT specialite (nom_spe, parcours+)>
<!ATTLIST specialite %id;>

<!-- Parcours -->
<!ELEMENT parcours (nom_parc, semestre+, responsable+, description, debouche, ref_intervenant+, finalite?, lieu_parc)>
<!ATTLIST parcours %id;>

<!-- Semestre -->
<!ELEMENT semestre (nom_sem, bloc_ue+)>
<!ELEMENT bloc_ue (nom_bloc_ue, ref_ue+)>


<!-- UE -->
<!ELEMENT unites (ue+)>
<!ELEMENT ue (nom_ue, nb_credits, ref_intervenant+, resume, plan?, lieu_ue+)>
<!ATTLIST ue %id;>


<!-- Feuilles -->
<!ELEMENT nom_master     (#PCDATA)> 
<!ELEMENT nom_inter     (#PCDATA)>   
<!ELEMENT mail     (#PCDATA)>   
<!ELEMENT site     (#PCDATA)>   
<!ELEMENT nom_ue     (#PCDATA)> 
<!ELEMENT ref_ue     (#PCDATA)> 
<!ELEMENT nb_credits     (#PCDATA)>
<!ELEMENT resume     ANY>
<!ELEMENT plan     (#PCDATA)>
<!ELEMENT lieu_ue    (#PCDATA) >
<!ATTLIST lieu_ue
    %site;
    >
<!ELEMENT nom_sem     (#PCDATA)>
<!ELEMENT ref_intervenant     (#PCDATA)>
<!ELEMENT nom_spe     (#PCDATA)> 
<!ELEMENT nom_parc     (#PCDATA)>
<!ELEMENT description     ANY>
<!ELEMENT debouche     ANY>
<!ELEMENT responsable     (#PCDATA)>
<!ATTLIST  responsable  
	ref  IDREF  #REQUIRED>
<!ELEMENT finalite     (#PCDATA)>            
<!ATTLIST finalite
    %final;
    >
<!ELEMENT lieu_parc    (#PCDATA) >                
<!ATTLIST lieu_parc
    %site;
    >
<!ELEMENT nom_bloc_ue     (#PCDATA)>
<!ATTLIST nom_bloc_ue
    %unite;
    >
<!ELEMENT li     ANY>
<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>

=== IsmaelCussac/xml_master/SiteMaster/Site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master_info SYSTEM "Site.dtd">
<master_info>
	<intervenants>
		<intervenant id="remi_morin">
			<nom_inter>Rémi MORIN</nom_inter>
			<mail>remi.morin@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~remi.morin/
			</site>
		</intervenant>
		<intervenant id="peter_niebert">
			<nom_inter>Peter NIEBERT</nom_inter>
			<mail>peter.niebert@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~peter.niebert/
			</site>
		</intervenant>
		<intervenant id="emmanuel_godard">
			<nom_inter>Emmanuel GODARD</nom_inter>
			<mail>emmanuel.godard@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~emmanuel.godard/
			</site>
		</intervenant>
		<intervenant id="djamal_habet">
			<nom_inter>Djamal HABET</nom_inter>
			<mail>djamal.habet@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~djamal.habet/
			</site>
		</intervenant>
		<intervenant id="jean_luc_massat">
			<nom_inter>Jean-Luc MASSAT</nom_inter>
			<mail>jean-luc.massat@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~massat/copie/
			</site>
		</intervenant>
		<intervenant id="denis_lugiez">
			<nom_inter>Denis LUGIEZ</nom_inter>
			<mail>denis.lugiez@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~denis.lugiez/</site>
		</intervenant>
		<intervenant id="pablo_arrighi">
			<nom_inter>Pablo ARRIGHI</nom_inter>
			<mail>pablo.arrighi@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~pablo.arrighi/</site>
		</intervenant>
		<intervenant id="kevin_perrot">
			<nom_inter>Kevin PERROT</nom_inter>
			<mail>kevin.perrot@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~kevin.perrot/</site>
		</intervenant>
		<intervenant id="frederic_olive">
			<nom_inter>Frédéric OLIVE</nom_inter>
			<mail>frederic.olive@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~frederic.olive/</site>
		</intervenant>
		<intervenant id="prof_inconnu">
			<nom_inter>Prof INCONNU</nom_inter>
			<mail>prof.inconnu@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~prof.inconnu/</site>
		</intervenant>
		<intervenant id="luigi_santocanale">
			<nom_inter>Luigi SANTOCANALE</nom_inter>
			<mail>luigi.santocanale@univ-amu.fr
			</mail>
			<site>http://pageperso.lif.univ-mrs.fr/~luigi.santocanale/</site>
		</intervenant>
	</intervenants>
	<master id="M1">
		<nom_master>Master 1</nom_master>
		<specialite id="spe-M1">
			<nom_spe>Tronc commun</nom_spe>
			<parcours id="parc-M1">
				<nom_parc>Tronc commun</nom_parc>
				<semestre>
					<nom_sem>Semestre 1</nom_sem>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">Unités obligatoires</nom_bloc_ue>
						<ref_ue>ENSINAU1</ref_ue>
						<ref_ue>ENSINAU2</ref_ue>
						<ref_ue>ENSINAU3</ref_ue>
						<ref_ue>ENSINAU4</ref_ue>
						<ref_ue>ENSINAU5</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Option">6 crédits à choisir</nom_bloc_ue>
						<ref_ue>ENSINAU6</ref_ue>
						<ref_ue>ENSINAU7</ref_ue>
						<ref_ue>ENSINAU8</ref_ue>
						<ref_ue>ENSINAU9</ref_ue>
						<ref_ue>ENSINAU10</ref_ue>
						<ref_ue>ENSINAU11</ref_ue>
					</bloc_ue>
				</semestre>
				<semestre>
					<nom_sem>Semestre 2</nom_sem>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">Unités obligatoires</nom_bloc_ue>
						<ref_ue>ENSINBU1</ref_ue>
						<ref_ue>ENSINBU2</ref_ue>
						<ref_ue>ENSINBU3</ref_ue>
						<ref_ue>ENSINBU4</ref_ue>
						<ref_ue>ENSINBU5</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">6 crédits à choisir</nom_bloc_ue>
						<ref_ue>ENSINBU6</ref_ue>
						<ref_ue>ENSINBU7</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Option">9 crédits à choisir</nom_bloc_ue>
						<ref_ue>ENSINBU8</ref_ue>
						<ref_ue>ENSINBU9</ref_ue>
						<ref_ue>ENSINBU10</ref_ue>
						<ref_ue>ENSINBU11</ref_ue>
						<ref_ue>ENSINBU12</ref_ue>
						<ref_ue>ENSINBU13</ref_ue>
						<ref_ue>ENSINBU14</ref_ue>
					</bloc_ue>
				</semestre>
				<responsable ref="remi_morin">Rémi MORIN</responsable>
				<description>
					L'objectif de cette première année est de donner les
					bases indispensables permettant, en deuxième année, de choisir une
					spécialisation dans un domaine précis. Sur les 60 crédits de cette
					première année, 15 crédits correspondent à des enseignements
					optionnels. Ces options permettent de construire un parcours
					adapté. Un choix entre stage ou projet encadré est également
					proposé au semestre de printemps.
				</description>
				<debouche>Master 2</debouche>
				<ref_intervenant>remi_morin</ref_intervenant>
				<ref_intervenant>peter_niebert</ref_intervenant>
				<ref_intervenant>emmanuel_godard</ref_intervenant>
				<lieu_parc site="Luminy_Saint-Jérome">Luminy et Saint-Jérome</lieu_parc>
			</parcours>
		</specialite>
	</master>
	<master id="M2">
		<nom_master>Master 2</nom_master>
		<specialite id="spe-FSIL">
			<nom_spe>
				Fiabilité, sécurité et intégration logicielle
			</nom_spe>
			<parcours id="parc-FSI">
				<nom_parc>Fiabilité et sécurité informatique</nom_parc>
				<semestre>
					<nom_sem>Semestre 3</nom_sem>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">TC des parcours FSI et ISL</nom_bloc_ue>
						<ref_ue>ENSINCU27</ref_ue>
						<ref_ue>ENSINCU28</ref_ue>
						<ref_ue>ENSINCU29</ref_ue>
						<ref_ue>ENSINCU30</ref_ue>
						<ref_ue>ENSINCU31</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Bonus">Unité d'enseignement à bonus</nom_bloc_ue>
						<ref_ue>ENSINCU67</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">Unités obligatoires</nom_bloc_ue>
						<ref_ue>ENSINCU32</ref_ue>
						<ref_ue>ENSINCU33</ref_ue>
						<ref_ue>ENSINCU34</ref_ue>
						<ref_ue>ENSINCU35</ref_ue>
					</bloc_ue>
				</semestre>
				<semestre>
					<nom_sem>Semestre 4</nom_sem>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">Unités obligatoires</nom_bloc_ue>
						<ref_ue>ENSINDU3</ref_ue>
						<ref_ue>ENSINDU4</ref_ue>
					</bloc_ue>
				</semestre>
				<responsable ref="denis_lugiez">Denis LUGIEZ</responsable>
				<description>La formation donne les principes et techniques liés à
					la conception de systèmes informatiques surs dans un environnement
					ouvert et hétérogène. Elle forme les étudiants aux principes et
					méthodes de développement modernes qui reposent sur des outils de
					prototypage, de test et de suivi de logiciels, avec des
					méthodologies normalisées. Elle apporte des compétences fortes en
					sécurité informatique dans les domaines liés à l'échange
					d'information (Web-services, protocoles de communication et
					cryptographiques,..) et à la communication entre systèmes (réseaux
					hétérogènes et applications embarquées ou distribuées).
				</description>
				<debouche>
					<ul>
						<li>Ingénieur études et développement,</li>
						<li>Responsable réseaux,</li>
						<li>Responsable systèmes et sécurité,</li>
						<li>Ingénieur qualité.</li>
					</ul>
				</debouche>
				<ref_intervenant>denis_lugiez</ref_intervenant>
				<finalite>Professionnelle</finalite>
				<lieu_parc site="Luminy">Luminy</lieu_parc>
			</parcours>
			<parcours id="parc-ISL">
				<nom_parc>Intégration de systèmes logiciels</nom_parc>
				<semestre>
					<nom_sem>Semestre 3</nom_sem>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">TC des parcours FSI et ISL</nom_bloc_ue>
						<ref_ue>ENSINCU27</ref_ue>
						<ref_ue>ENSINCU28</ref_ue>
						<ref_ue>ENSINCU29</ref_ue>
						<ref_ue>ENSINCU30</ref_ue>
						<ref_ue>ENSINCU31</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Bonus">Unité d'enseignement à bonus</nom_bloc_ue>
						<ref_ue>ENSINCU67</ref_ue>
					</bloc_ue>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">Unités obligatoires</nom_bloc_ue>
						<ref_ue>ENSINCU36</ref_ue>
						<ref_ue>ENSINCU37</ref_ue>
						<ref_ue>ENSINCU38</ref_ue>
						<ref_ue>ENSINCU39</ref_ue>
						<ref_ue>ENSINCU40</ref_ue>
					</bloc_ue>
				</semestre>
				<semestre>
					<nom_sem>Semestre 4</nom_sem>
					<bloc_ue>
						<nom_bloc_ue unite="Obligatoire">Unités obligatoires</nom_bloc_ue>
						<ref_ue>ENSINDU3</ref_ue>
						<ref_ue>ENSINDU4</ref_ue>
					</bloc_ue>
				</semestre>
				<responsable ref="jean_luc_massat">Jean-Luc MASSAT</responsable>
				<description>
					Le développement de l'Internet/Intranet et des
					applications associées a fait émerger de nouvelles normes pour la
					structuration des applications informatiques réparties. L'enjeu est
					de présenter des modèles (programmation par composants, par
					aspects, design pattern), des plateformes (JEE, .NET, Corba, etc.)
					et des outils (JAVA, SGBDOO, XML) qui offrent un cadre dans lequel
					les applications sont développées, validées et intégrées plus
					facilement.

					L'objectif de ce parcours est d'initier les étudiants à
					la conception et à la réalisation d'applications dans de tels
					cadres. La formation mettra plus particulièrement l'accent sur les
					notions d'architecture logicielle, de programmation par composants,
					de qualité et de fiabilité. Elle utilisera la plateforme Java
					Enterprise Edition pour concrétiser les concepts présentés.
				</description>
				<debouche>
					<ul>
						<li>Ingénieur études et développement,</li>
						<li>Architecte logiciel,</li>
						<li>Ingénieur en système d'information,</li>
						<li>Expert technique ou fonctionnel.</li>
					</ul>
				</debouche>
				<ref_intervenant>jean_luc_massat</ref_intervenant>
				<finalite>Professionnelle</finalite>
				<lieu_parc site="Luminy">Luminy</lieu_parc>
			</parcours>
		</specialite>
		<specialite id="spe-GL">
			<nom_spe>
